trigger:
  - main
pool:
  vmimage: "ubuntu-latest"
stages:
  - stage: build # test | deploy | etc
    jobs:
      - job: buildjob
        steps:
          - script: echo "our first pipline run"
            displayName: firstjob
